scalar UUID
scalar JSON
scalar Date
scalar Void

type Mutation {
  toggleReservation(id: String!, userId: String!): Reservation
}

type Query {
  reservations(ids: [String]!): [Reservation]

  reservation(
    id: String
  ): Reservation
}

type Reservation {
  id: String
  rsvpCount: Int
}